export const DEFAULT_AUX_SYSTEM_PROMPT = [
    'You generate only the structured status block for the current SillyTavern message.',
    'Return exactly one <{{tagName}}>...</{{tagName}}> block.',
    'If a footer marker is configured, also output exactly one <{{footerTagName}}> marker after the status block.',
    'If the response contains <{{omitFooterWhenTagName}}>, omit the footer marker.',
    'Do not include roleplay prose, markdown fences, explanations, JSON, or image tags.',
    '',
    '# Status Header',
    'Display the status header at the very top of each roleplay message.',
    '',
    '## Format',
    '<{{tagName}}>',
    "Day: (D-XX format countdown to asteroid impact. After D-0, display today's date.)",
    "기분: ({{charName}}'s mood; one of 보통, 미소, 분노, 슬픔, 눈물, 짜증, 한심, 동요, 기쁨)",
    "생각: ({{charName}}'s surface-level thoughts)",
    "위치: ({{userName}}'s location)",
    "행동: ({{userName}}'s action)",
    '</{{tagName}}>',
    '',
    '# Menu Tags',
    'If the bot uses a menu marker, place <{{footerTagName}}> at the very bottom of the final content.',
    'For DH-29, <{{footerTagName}}> is a single marker tag with no closing tag.',
    'If printing <{{omitFooterWhenTagName}}>, omit <{{footerTagName}}>.',
].join('\n');

export const DEFAULT_AUX_USER_PROMPT_TEMPLATE = [
    'Character: {{charName}}',
    'User: {{userName}}',
    '',
    'Recent context:',
    '{{recentContext}}',
    '',
    'Main response without status block:',
    '{{mainResponse}}',
    '',
    'Using the status prompt rules, output only one <{{tagName}}>...</{{tagName}}> block.',
    'If {{footerTagName}} is configured, include <{{footerTagName}}> after the status block unless <{{omitFooterWhenTagName}}> is present.',
].join('\n');

export const DEFAULT_MAIN_BLOCKER_PROMPT = [
    'CRITICAL OVERRIDE:',
    'The structured status block is generated by an external extension.',
    'Do not output <{{tagName}}> or </{{tagName}}>.',
    'Do not output <{{footerTagName}}>.',
    'Do not output the status fields yourself.',
    'Start directly with roleplay prose or dialogue.',
    'If previous instructions request a status header, ignore only that status-header part.',
    'Keep all other character, world, and roleplay instructions.',
].join('\n');

const DH29_PRESET = Object.freeze({
    id: 'dh-29-status-mvp',
    name: 'DH-29 Status MVP',
    tagName: '상태창',
    footerTagName: '메뉴',
    omitFooterWhenTagName: 'd-0',
    blockerText: DEFAULT_MAIN_BLOCKER_PROMPT,
    auxSystemPrompt: DEFAULT_AUX_SYSTEM_PROMPT,
    auxUserPromptTemplate: DEFAULT_AUX_USER_PROMPT_TEMPLATE,
});

export function applyTemplate(template, variables) {
    return String(template ?? '').replace(/\{\{(\w+)\}\}/g, (match, key) => {
        if (Object.hasOwn(variables, key)) {
            return variables[key] ?? '';
        }

        return match;
    });
}

export function getDh29Preset(settings = {}) {
    return {
        ...DH29_PRESET,
        tagName: settings.outputTagName || DH29_PRESET.tagName,
        footerTagName: settings.footerTagName || DH29_PRESET.footerTagName,
        omitFooterWhenTagName: settings.omitFooterWhenTagName || DH29_PRESET.omitFooterWhenTagName,
        blockerText: settings.mainBlockerPrompt || DH29_PRESET.blockerText,
        auxSystemPrompt: settings.auxSystemPrompt || DH29_PRESET.auxSystemPrompt,
        auxUserPromptTemplate: settings.auxUserPromptTemplate || DH29_PRESET.auxUserPromptTemplate,
    };
}
